excluded:
- Pods

line_length:
- 250 # warning
- 300 # error

type_body_length:
  - 300 # warning
  - 400 # error

identifier_name:
  min_length: 3 # only min_length
  excluded: # excluded via string array
    - id
    - URL

function_body_length:
    - 50 # warning
    - 70 # error
    
cyclomatic_complexity: 20

disabled_rules: # rule identifiers to exclude from running
 - force_cast
 - force_try
 - multiple_closures_with_trailing_closure
